{% set name = "bamnostic" %}
{% set version = "1.0.12" %}
{% set sha256 = "e158965313cba7deca3dbccf9a91b49f652ac55aa75362fec7891bd464043c2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - setuptools
  imports:
    - bamnostic

about:
  home: https://github.com/betteridiot/bamnostic
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a pure Python, OS-agnositic Binary Alignment Map (BAM) file parser and random access tool.

extra:
  recipe-maintainers:
    - betteridiot
    - ericmjl
