{% set name = "bamnostic" %}
{% set version = "1.0.2" %}
{% set sha256 = "92368d6c7ec1fabebcd56b548fa24d21be74663f5ece7b0b59b6de2b5f66b39c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - bamnostic
  requires:
    - pytest
  commands:
    - py.test 
    - py.test --doctest-modules -Wignore

about:
  home: https://github.com/betteridiot/bamnostic
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a pure Python, OS-agnositic Binary Alignment Map (BAM) file parser and random access tool.

extra:
  recipe-maintainers:
    - betteridiot
    - ericmjl
