{% set name = "bamnostic" %}
{% set version = "1.1.10" %}
{% set sha256 = "2f7e7e5cb693c5f933c5b5c3fde49c6c8dee62b608ebd13a4604401573e37017" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7

test:
  requires:
    - setuptools
  imports:
    - bamnostic

about:
  home: https://github.com/betteridiot/bamnostic
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a pure Python, OS-agnositic Binary Alignment Map (BAM) file parser and random access tool.

extra:
  recipe-maintainers:
    - betteridiot
    - ericmjl
