{% set name = "bamnostic" %}
{% set version = "0.8.4" %}
{% set sha256 = "369137de5a4f82529fb1e3a2c7bea13eea1034b1f189b95250ba493acbc449d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest
    - markdown

test:
  imports:
    - bamnostic

about:
  home: https://github.com/betteridiot/bamnostic
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a pure Python, OS-agnositic Binary Alignment Map (BAM) file parser and random access tool.

extra:
  recipe-maintainers:
    - betteridiot
    - ericmjl
