travis:
  secure:
    BINSTAR_TOKEN: lxkGP4br7kuXR+yWnvipRDqOUVe+BFLgAcRTh/jbu+U6lQ8WJChlQtCw0k+848Jzd30AUOTXeaeVMukishb6x7+dlu9uzqMDiOrvzOI13PknaSxTAA41DUdsVY3MBnR57bVGDe8Sr4OiHDbDB6mCqfGaio59w2OrkOeYK/wtJCX2J8RPgiYbwoSUa8LEFT888FxVyn1QLw5KsxR5bHom/mPYmnrmmkCMNgjZyZ+TV31ufnnmkZo2ayxgYzLiBrBEP5XcdUk7/H7r30AfPggEpX3SDGd5hR8R1PeouHrN/ZGfhJWIzGlRlrkSS/bJFLTl8Zbm42LWYQnx6YOXTREkcqkGUJ+zdWEjaxsTC4fWsJ2HadJwbvy3WAanoJMq6G8gaTe/Y9dBnfKdPUdyj7Cp8Z+tv0mF40lax9b5+Qw+wlZP9/yS6wogFrU9UMeP3bC/ORz56Mg6Wo/YQQ83DvBSGs9CVB/auGfPw7FAZzWbJ5rF7TIZr/Bpax+NhON+ZI9Dttk/HNLVuf9Xd+Dlqic9CEniJQUFZvda8pPK8MaBjtoYocLxI58F/3ahaCHiw4xLesKokEf3h4HbCLxirT7YiL6SJaW6fGvTCCASYCOhuST3ZqjujniGjexJ0Rj0X1cfubv22rtcYrcmq+UMU/zezWrU2EnkurecsVzFSPVW+Lc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
