travis:
  secure:
    BINSTAR_TOKEN: NI4GHqJEDNXZjO3Vjhzjp1a5LX42AcrHPin8DEk0Bd4F1TAP85tZzt3hVf9ugKAHI11Dh+QYlk34R6OfuDXY7wfyLFM4bsijlTfQSdet7GMMWDcVEPA9fbGfOD2bYcmPlBAA0zIqPtDwGEXbtXUvdxPraZlZN/P2SE+7c7Fxrw0WxIffO4cC5PgS4zsa5dMT+UrQsf8TvlHoWZEWTuMy1ppDzD/rMcAbx3pfZTl42aDORUmrzb7JuHf+RqrL3+pMDqB2om1DKVrsOrD0fr5b6FemXVw2UneFOIIVR+mSCdr6eNsE+evgngyb+hseoCizBhuqEHAmSwI8pDI/hM26QYWMOMRuNCeTyHXvCsAP0UYDc0v8XDasbYm/SeVzlJ2/Xs1eO9SMvoJQIsDMT+Pmo9NzBTgWDK+L+DAgcxy9BmrfGsx84+5OAkdBWCWKX90o5CONs7rvRkURFEx0RKIsndSDy3fiE2Lho2viBPEqL9Evk+sMA3+KK+iczAbpZJbBj5IvNBDnik40jbNzR4payrLsEfkaOCvJKYIOkKBJgO+e8oXKrj0fg8mBzYyzRjl76XHNjXws11Ovt9j8glibU7leeLpTufYZQygs32G+nZFuIJYI17uKl4nK3H6d7EBF1YBiyY9ylB+YZaTW+t+m+4zh7QHiPAmlmDmW5ptx6LU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
